name: python-app
on: [push]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup haskell
        working-directory: ./simply-typed
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8'
          cabal-version: '3.3.0.0'
      - name: run tests
        run: make tests
